Array Creation

In [3]:
import numpy as np

In [ ]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [2]:
a.dtype

dtype('int32')

In [4]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [7]:
b.dtype

dtype('float64')

* array: can be tranforms sequence of sequence into tow-dimonsional array tree-dimonsion, and so on.

In [9]:
b = np.array([(1.4, 2, 3), (4, 5, 6)])
b

array([[1.4, 2. , 3. ],
       [4. , 5. , 6. ]])

Function

* zero: create an array full of zeros
* ones: create an array full of one
* empty: creates content is random and depend on the state of the memory.

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty((2,3))

array([[1.4, 2. , 3. ],
       [4. , 5. , 6. ]])